<a href="https://colab.research.google.com/github/osmanatam/33-js-concepts/blob/master/Python_and_Machine_Learning_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = ["Banana", "Tomatoes", "Peas", "Apples", "Cabbage"]

In [ ]:
a

['Banana', 'Tomatoes', 'Peas', 'Apples', 'Cabbage']

In [ ]:
type(a)

list

In [ ]:
lis = [1, 1.0, 'Hello', True]

In [ ]:
a = 'Hello'
b = 'World'

In [ ]:
a

'Hello'

In [1]:
b

NameError: ignored

In [ ]:
lis = ['Hello', 'World', 'Hello']

In [ ]:
lis

['Hello', 'World']

In [ ]:
lis[1]

'World'

In [ ]:
lis[0]

'Hello'

In [ ]:
a = 'Hello World'

In [ ]:
a[5]

' '

In [ ]:
a[0:2]

'He'

In [ ]:
a[6:8]

'Wo'

In [ ]:
lis

['Hello', 'World', 'Hello']

In [ ]:
# list_name.append(element)
lis.append('Bbye')

In [ ]:
lis

['Hello', 'World', 'Hello', 'Bbye']

In [ ]:
lis[2]

'Hello'

In [ ]:
lis[2] = 'Good Night'

In [ ]:
lis

['Hello', 'World', 'Good Night', 'Bbye']

In [ ]:
del lis[1]

In [ ]:
lis

['Hello', 'Good Night', 'Bbye']

In [ ]:
CRUD -> List

In [ ]:
dic = {'Phone':"An item that has some functionality"}

In [ ]:
type(dic)

dict

In [ ]:
dic

{'Phone': 'An item that has some functionality'}

In [ ]:
asd = {'Pencil':["A", "B", "C"]}

In [ ]:
asd

{'Pencil': ['A', 'B', 'C']}

In [ ]:
asd = {'Pencil':{"A":"B", "C":"D"}}

In [ ]:
asd

{'Pencil': {'A': 'B', 'C': 'D'}}

In [ ]:
asd.keys()

dict_keys(['Pencil'])

In [ ]:
asd.values()

dict_values([{'A': 'B', 'C': 'D'}])

In [ ]:
asd['Pencil']

{'A': 'B', 'C': 'D'}

In [ ]:
lisi = [1,2,3,4,1,2,3]
si = {1,2,3,4,1,2,3}

In [ ]:
lisi

[1, 2, 3, 4, 1, 2, 3]

In [ ]:
si

{1, 2, 3, 4}

In [ ]:
a = (1,2,3,4,5,6)

In [ ]:
type(a)

tuple

In [ ]:
IND = 1

In [ ]:
if IND=='WIN':
  print('He will give Rs. 500/-')
elif IND == 'LOSE':
  print('I will give Rs. 500/-')
else:
  print('No one will gonna pay')

No one will gonna pay


In [ ]:
# For loop
# Nested Loop - Loop in a loop
for i in range(0,10):
  for j in range(0,5):
    print(i,j)


0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4
5 0
5 1
5 2
5 3
5 4
6 0
6 1
6 2
6 3
6 4
7 0
7 1
7 2
7 3
7 4
8 0
8 1
8 2
8 3
8 4
9 0
9 1
9 2
9 3
9 4


In [ ]:
0
1
2
3
4
5
6
7
8
9

In [ ]:
count = 0

In [ ]:
while count < 10:
  print('Hello', count)
  count += 1

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9


In [ ]:
10 < 10

In [ ]:
import time
import numpy as np

In [ ]:
a = np.random.rand(1000000000)

In [ ]:
a

array([0.05310729, 0.43481836, 0.01209359, ..., 0.82650075, 0.88065819,
       0.21975354])

In [ ]:
len(a)

1000000000

In [ ]:
# NumPy
start = time.time()
mean_np = np.mean(a)
print(time.time() - start)

0.9870448112487793


In [ ]:
# List
start = time.time()
mean_list = sum(a)/len(a)
print(time.time() - start)

178.1957302093506


In [ ]:
NumPy - Approx. 1 Sec
List - Approx. 3 mins

In [ ]:
mean_np

0.4999963986575125

In [ ]:
mean_list

0.4999963986575889

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.ndim

1

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
a.ndim

2

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b = np.array([a])

In [ ]:
b.ndim

3

In [ ]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
b

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Regression/master/IceCreamData.csv')

In [ ]:
df

Temperature     Revenue
0      24.566884  534.799028
1      26.005191  625.190122
2      27.790554  660.632289
3      20.595335  487.706960
4      11.503498  316.240194
..           ...         ...
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

[500 rows x 2 columns]

In [ ]:
df.head(10)

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194
5    14.352514  367.940744
6    13.707780  308.894518
7    30.833985  696.716640
8     0.976870   55.390338
9    31.669465  737.800824

In [ ]:
df.tail(10)

Temperature     Revenue
490    23.824922  584.399945
491    34.472169  809.352520
492    23.056214  552.819351
493    14.931506  377.430928
494    25.112066  571.434257
495    22.274899  524.746364
496    32.893092  755.818399
497    12.588157  306.090719
498    22.362402  566.217304
499    28.957736  655.660388

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [ ]:
df.describe()

Temperature      Revenue
count   500.000000   500.000000
mean     22.232225   521.570777
std       8.096388   175.404751
min       0.000000    10.000000
25%      17.122258   405.558681
50%      22.392791   529.368565
75%      27.740674   642.257922
max      45.000000  1000.000000

In [ ]:
df.ndim

2

In [ ]:
model = LinearRegression()

In [ ]:
X = df['Temperature']
y = df['Revenue']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [ ]:
len(X_train)

375

In [ ]:
len(X_test)

125

In [ ]:
len(y_train)

375

In [ ]:
len(y_test)

125

In [ ]:
X_train.ndim

1

In [ ]:
X_train = np.array([X_train])

In [ ]:
X_train.ndim

2

In [ ]:
model.fit(X_train.reshape(-1,1), y_train)

LinearRegression()

In [ ]:
X_test = np.array([X_test])

In [ ]:
y_pred = model.predict(X_test.reshape(-1,1))

In [ ]:
r2_score(y_test, y_pred)

0.979012417456737

# Python and Machine Learning Bootcamp


* Attendence Link: https://forms.gle/TeV46117KLER1kRQ8

* Project Submission Link: https://forms.gle/ZFchxwhTieUUrsFy7

* Dataset Link: https://drive.google.com/file/d/1v4vNMRqztdsDjOz8t-yQujKR6UpH0ocb/view?usp=sharing

* DevTown Link: https://www.devtown.in/



In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Python and Data Analytics Bootcamp 09.21/Housing Dataset.csv')

In [ ]:
df.head()

price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [ ]:
df.mainroad.value_counts()

yes    468
no      77
Name: mainroad, dtype: int64

In [ ]:
yes - 1
no - 0

In [ ]:
df.furnishingstatus.value_counts()

semi-furnished    227
unfurnished       178
furnished         140
Name: furnishingstatus, dtype: int64

In [ ]:
semi-furnished - 2
furnished - 1
unfurnished - 0

In [ ]:
model = LinearRegression()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB
